import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import {
  buildCatalogSeedSql,
  normalizeCatalog,
  type CatalogExerciseInput,
} from '../utils/catalogNormalizer.ts';

const SOURCE_REPO = 'yuhonas/free-exercise-db';
const SOURCE_FILE = 'dist/exercises.json';

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

async function fetchJson<T>(url: string): Promise<T> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`GET ${url} failed: ${response.status} ${response.statusText}`);
  }
  return response.json() as Promise<T>;
}

const sourceCommitSha = async (): Promise<string> => {
  const latest = await fetchJson<{ sha: string }>(
    `https://api.github.com/repos/${SOURCE_REPO}/commits/main`,
  );
  return latest.sha;
};

const DEMO_CATALOG_KEYS = [
  'Barbell_Full_Squat',
  'Barbell_Bench_Press_-_Medium_Grip',
  'Barbell_Deadlift',
  'Barbell_Shoulder_Press',
  'Wide-Grip_Lat_Pulldown',
  'Bent_Over_Two-Dumbbell_Row',
  'Lying_Leg_Curls',
];

const buildFixture = (
  exercises: readonly CatalogExerciseInput[],
): CatalogExerciseInput[] => {
  const byId = new Map(exercises.map((e) => [e.id, e]));
  const slice = DEMO_CATALOG_KEYS.map((key) => byId.get(key) ?? exercises[0])
    .concat(exercises.slice(0, 7))
    .map((e) => ({ ...e, primaryMuscles: [...e.primaryMuscles], secondaryMuscles: [...e.secondaryMuscles] }));
  slice.push({ ...slice[0], id: '3_4_Sit_Up_Duplicate' });
  return slice;
};

const buildSeedFile = (
  exercises: ReturnType<typeof normalizeCatalog>['exercises'],
): string => {
  const exerciseRows = exercises.map((e) => ({
    exercise_key: e.exerciseKey,
    name: e.name,
    category: e.category,
    level: e.level,
    force: e.force,
    mechanic: e.mechanic,
    equipment: e.equipment,
    instructions: e.instructions,
  }));
  const muscleRows = exercises.flatMap((e) =>
    e.muscles.map((m) => ({
      exercise_key: e.exerciseKey,
      muscle_name: m.muscleName,
      is_primary: m.isPrimary ? 1 : 0,
    })),
  );

  const exerciseSql = buildCatalogSeedSql(
    'Catalog_Exercises',
    [
      'exercise_key',
      'name',
      'category',
      'level',
      'force',
      'mechanic',
      'equipment',
      'instructions',
    ],
    exerciseRows,
  );
  const muscleSql = buildCatalogSeedSql(
    'Catalog_Exercise_Muscles',
    ['exercise_key', 'muscle_name', 'is_primary'],
    muscleRows,
  );

  return `// Generated by scripts/ingest-catalog.ts — do not edit by hand.
// Source: ${SOURCE_REPO} @ ${SOURCE_FILE}. See data/catalog-manifest.json.

export const CATALOG_EXERCISE_SEED_SQL: string = ${JSON.stringify(exerciseSql)};

export const CATALOG_MUSCLE_SEED_SQL: string = ${JSON.stringify(muscleSql)};
`;
};

const main = async (): Promise<void> => {
  const sha = await sourceCommitSha();
  const raw = await fetchJson<CatalogExerciseInput[]>(
    `https://raw.githubusercontent.com/${SOURCE_REPO}/${sha}/${SOURCE_FILE}`,
  );

  const normalized = normalizeCatalog(raw);
  const fixture = buildFixture(raw);
  const manifest = {
    source: SOURCE_REPO,
    file: SOURCE_FILE,
    commit: sha,
    fetchedAt: new Date().toISOString(),
    rawCount: raw.length,
    keptCount: normalized.exercises.length,
    droppedDuplicates: normalized.droppedDuplicates,
  };

  await writeFile(
    join(projectRoot, 'data', 'catalog-seed.ts'),
    buildSeedFile(normalized.exercises),
  );
  await writeFile(
    join(projectRoot, 'data', 'catalog-manifest.json'),
    `${JSON.stringify(manifest, null, 2)}\n`,
  );
  await writeFile(
    join(projectRoot, 'data', 'catalog-fixture.json'),
    `${JSON.stringify(fixture, null, 1)}\n`,
  );

  console.log(
    `catalog ingested: raw ${manifest.rawCount} -> kept ${manifest.keptCount} ` +
      `(dropped ${manifest.droppedDuplicates}) @ ${sha}`,
  );
};

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
